### ISSUE TITLE
Move all server messages to bundles

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#149] opened 2024-05-09 16:10 UTC
### What you are suggesting

Should also make a russian bundle so they can read shit

**Comment by phinner** [comment] 2024-05-09 22:53
Duplicate of https://github.com/xpdustry/imperium/issues/63

**Closed by phinner** 2024-05-09 22:53 UTC
Labels: enhancement

**Comment by JasonP01** [comment] 2024-05-09 23:35
Fr? Thought i looked for duplicate, my bad
